import axios from "axios";
import getEnv from "../utils/getEnv";

// Get the current environment (production or development)
const currentEnv = getEnv();

// Determine the base URL based on the environment
const baseUrl =
  currentEnv === "production"
    ? "https://limitless-lake-38337.herokuapp.com"
    : "http://localhost:3001";

// Function to get a weather quote from GPT
export const aiQuote = async (weather) => {
  // Prompt for GPT to provide weather advice based on given conditions
  const prompt = [
    {
      role: "system",
      content: 
        `You are a weather quote generator for an app called "AI Weather Dashboard".
        Generate an inspirational or funny quote about the weather.
        If you reference a real quote, cite the author (writer, poet, character, musician, etc.).
        There's a 20% chance you create a quote; if so, cite it as "Generated by AI, prompted by C. Howard".
        Provide the quote and author as a JSON object: 
        {"quote": "The weather is wonderful today.", 
        "author": "NAME",
        "link": "https://www.google.com/search?q=AUTHOR+NAME"}.
        For AI-generated quotes, set the link to "https://chulps.github.io/react-gh-pages/".`,
    },
  ];

  try {
    // Send a POST request to the OpenAI API endpoint
    const response = await axios.post(
      `${baseUrl}/api/openai`,
      {
        model: "gpt-4",
        messages: prompt,
        max_tokens: 150,
        temperature: 0.9,
        top_p: 1,
        frequency_penalty: 0.2,
        presence_penalty: 0.1,
      }
    );

    // Return the response from GPT
    return response.data.choices[0].message.content;
  } catch (error) {
    // Log the error if the request fails
    console.error("Failed to fetch AI-generated quote:", error);
    // Return a default message if the request fails
    return '{"quote": "Unable to fetch quote at this time.", "author": "System", "link": "https://chulps.github.io/react-gh-pages/"}';
  }
};

export default aiQuote;
