// languages.js
export const languages = [
  { value: 'af', label: '🇿🇦 Afrikaans', keywords: ['afrikaans', 'south africa'] },
  { value: 'sq', label: '🇦🇱 Shqip', keywords: ['albanian', 'shqip', 'albania'] },
  { value: 'am', label: '🇪🇹 አማርኛ', keywords: ['amharic', 'ethiopian'] },
  { value: 'ar', label: '🇸🇦 العربية', keywords: ['arabic', 'arab', 'saudi arabia', 'عربى'] },
  { value: 'hy', label: '🇦🇲 Հայերեն', keywords: ['armenian', 'armenia', 'հայերեն'] },
  { value: 'az', label: '🇦🇿 Azərbaycanca', keywords: ['azerbaijani', 'azerbaijan', 'azərbaycan dili'] },
  { value: 'eu', label: '🇪🇸 Euskara', keywords: ['basque', 'euskara', 'spain', 'euskara'] },
  { value: 'be', label: '🇧🇾 Беларуская', keywords: ['belarusian', 'belarus', 'беларуская'] },
  { value: 'bn', label: '🇧🇩 বাংলা', keywords: ['bengali', 'bangla', 'bangladesh', 'বাংলা'] },
  { value: 'bs', label: '🇧🇦 Bosanski', keywords: ['bosnian', 'bosnia', 'bosanski'] },
  { value: 'bg', label: '🇧🇬 Български', keywords: ['bulgarian', 'bulgaria', 'български'] },
  { value: 'ca', label: '🇪🇸 Català', keywords: ['catalan', 'catalonia', 'spain', 'català'] },
  { value: 'ceb', label: '🇵🇭 Cebuano', keywords: ['cebuano', 'philippines'] },
  { value: 'zh-CN', label: '🇨🇳 中文 (简体)', keywords: ['chinese', 'simplified chinese', 'china', '中文 (简体)', '汉语'] },
  { value: 'zh-TW', label: '🇹🇼 中文 (繁體)', keywords: ['chinese', 'traditional chinese', 'taiwan', '中文 (繁體)', '漢語'] },
  { value: 'co', label: '🇫🇷 Corsu', keywords: ['corsican', 'corsica', 'france', 'corsu'] },
  { value: 'hr', label: '🇭🇷 Hrvatski', keywords: ['croatian', 'croatia', 'hrvatski'] },
  { value: 'cs', label: '🇨🇿 Čeština', keywords: ['czech', 'czechia', 'czech republic', 'čeština'] },
  { value: 'da', label: '🇩🇰 Dansk', keywords: ['danish', 'denmark', 'dansk'] },
  { value: 'nl', label: '🇳🇱 Nederlands', keywords: ['dutch', 'netherlands', 'holland', 'nederlands'] },
  { value: 'en', label: '🇺🇸 English', keywords: ['english', 'usa', 'america'] },
  { value: 'eo', label: '🇺🇳 Esperanto', keywords: ['esperanto'] },
  { value: 'et', label: '🇪🇪 Eesti', keywords: ['estonian', 'estonia', 'eesti'] },
  { value: 'fi', label: '🇫🇮 Suomi', keywords: ['finnish', 'finland', 'suomi'] },
  { value: 'fr', label: '🇫🇷 Français', keywords: ['french', 'france', 'français'] },
  { value: 'fy', label: '🇳🇱 Frysk', keywords: ['frisian', 'friesland', 'netherlands', 'frysk'] },
  { value: 'gl', label: '🇪🇸 Galego', keywords: ['galician', 'galicia', 'spain', 'galego'] },
  { value: 'ka', label: '🇬🇪 ქართული', keywords: ['georgian', 'georgia', 'ქართული'] },
  { value: 'de', label: '🇩🇪 Deutsch', keywords: ['german', 'germany', 'deutsch'] },
  { value: 'el', label: '🇬🇷 Ελληνικά', keywords: ['greek', 'greece', 'ελληνικά'] },
  { value: 'gu', label: '🇮🇳 ગુજરાતી', keywords: ['gujarati', 'india', 'ગુજરાતી'] },
  { value: 'ht', label: '🇭🇹 Kreyòl ayisyen', keywords: ['haitian creole', 'haiti', 'kreyòl ayisyen'] },
  { value: 'ha', label: '🇳🇬 Hausa', keywords: ['hausa', 'nigeria'] },
  { value: 'haw', label: '🇺🇸 Hawaiʻi', keywords: ['hawaiian', 'hawaii', 'usa', 'hawaiʻi'] },
  { value: 'he', label: '🇮🇱 עברית', keywords: ['hebrew', 'israel', 'עברית'] },
  { value: 'hi', label: '🇮🇳 हिंदी', keywords: ['hindi', 'india', 'हिंदी'] },
  { value: 'hmn', label: '🇨🇳 Hmoob', keywords: ['hmong', 'china', 'hmoob'] },
  { value: 'hu', label: '🇭🇺 Magyar', keywords: ['hungarian', 'hungary', 'magyar'] },
  { value: 'is', label: '🇮🇸 Íslenska', keywords: ['icelandic', 'iceland', 'íslenska'] },
  { value: 'ig', label: '🇳🇬 Igbo', keywords: ['igbo', 'nigeria'] },
  { value: 'id', label: '🇮🇩 Bahasa Indonesia', keywords: ['indonesian', 'indonesia', 'bahasa indonesia'] },
  { value: 'ga', label: '🇮🇪 Gaeilge', keywords: ['irish', 'ireland', 'gaeilge'] },
  { value: 'it', label: '🇮🇹 Italiano', keywords: ['italian', 'italy', 'italiano'] },
  { value: 'ja', label: '🇯🇵 日本語', keywords: ['japanese', 'japan', '日本語', 'nihongo'] },
  { value: 'jw', label: '🇮🇩 Basa Jawa', keywords: ['javanese', 'java', 'indonesia', 'basa jawa'] },
  { value: 'kn', label: '🇮🇳 ಕನ್ನಡ', keywords: ['kannada', 'india', 'ಕನ್ನಡ'] },
  { value: 'kk', label: '🇰🇿 Қазақ тілі', keywords: ['kazakh', 'kazakhstan', 'қазақ тілі'] },
  { value: 'km', label: '🇰🇭 ខ្មែរ', keywords: ['khmer', 'cambodia', 'ខ្មែរ'] },
  { value: 'rw', label: '🇷🇼 Kinyarwanda', keywords: ['kinyarwanda', 'rwanda'] },
  { value: 'ko', label: '🇰🇷 한국어', keywords: ['korean', 'korea', '한국어'] },
  { value: 'ku', label: '🇹🇷 Kurdî', keywords: ['kurdish', 'kurdistan', 'kurdî'] },
  { value: 'ky', label: '🇰🇬 Кыргызча', keywords: ['kyrgyz', 'kyrgyzstan', 'кыргызча'] },
  { value: 'lo', label: '🇱🇦 ລາວ', keywords: ['lao', 'laos', 'ລາວ'] },
  { value: 'la', label: '🇻🇦 Latina', keywords: ['latin', 'vatican', 'latina'] },
  { value: 'lv', label: '🇱🇻 Latviešu', keywords: ['latvian', 'latvia', 'latviešu'] },
  { value: 'lt', label: '🇱🇹 Lietuvių', keywords: ['lithuanian', 'lithuania', 'lietuvių'] },
  { value: 'lb', label: '🇱🇺 Lëtzebuergesch', keywords: ['luxembourgish', 'luxembourg', 'lëtzebuergesch'] },
  { value: 'mk', label: '🇲🇰 Македонски', keywords: ['macedonian', 'macedonia', 'македонски'] },
  { value: 'mg', label: '🇲🇬 Malagasy', keywords: ['malagasy', 'madagascar'] },
  { value: 'ms', label: '🇲🇾 Bahasa Melayu', keywords: ['malay', 'malaysia', 'bahasa melayu'] },
  { value: 'ml', label: '🇮🇳 മലയാളം', keywords: ['malayalam', 'india', 'മലയാളം'] },
  { value: 'mt', label: '🇲🇹 Malti', keywords: ['maltese', 'malta', 'malti'] },
  { value: 'mi', label: '🇳🇿 Māori', keywords: ['maori', 'new zealand', 'māori'] },
  { value: 'mr', label: '🇮🇳 मराठी', keywords: ['marathi', 'india', 'मराठी'] },
  { value: 'mn', label: '🇲🇳 Монгол', keywords: ['mongolian', 'mongolia', 'монгол'] },
  { value: 'my', label: '🇲🇲 မြန်မာ', keywords: ['burmese', 'myanmar', 'မြန်မာ'] },
  { value: 'ne', label: '🇳🇵 नेपाली', keywords: ['nepali', 'nepal', 'नेपाली'] },
  { value: 'no', label: '🇳🇴 Norsk', keywords: ['norwegian', 'norway', 'norsk'] },
  { value: 'ny', label: '🇲🇼 Chichewa', keywords: ['chichewa', 'nyanja', 'malawi'] },
  { value: 'or', label: '🇮🇳 ଓଡ଼ିଆ', keywords: ['odia', 'orissa', 'india', 'ଓଡ଼ିଆ'] },
  { value: 'ps', label: '🇦🇫 پښتو', keywords: ['pashto', 'afghanistan', 'پښتو'] },
  { value: 'fa', label: '🇮🇷 فارسی', keywords: ['persian', 'farsi', 'iran', 'فارسی'] },
  { value: 'pl', label: '🇵🇱 Polski', keywords: ['polish', 'poland', 'polski'] },
  { value: 'pt', label: '🇵🇹 Português', keywords: ['portuguese', 'portugal', 'português'] },
  { value: 'pa', label: '🇮🇳 ਪੰਜਾਬੀ', keywords: ['punjabi', 'india', 'ਪੰਜਾਬੀ'] },
  { value: 'ro', label: '🇷🇴 Română', keywords: ['romanian', 'romania', 'română'] },
  { value: 'ru', label: '🇷🇺 Русский', keywords: ['russian', 'russia', 'русский'] },
  { value: 'sm', label: '🇼🇸 Gagana Samoa', keywords: ['samoan', 'samoa', 'gagana samoa'] },
  { value: 'gd', label: '🏴 Gàidhlig', keywords: ['scots gaelic', 'scotland', 'gàidhlig'] },
  { value: 'sr', label: '🇷🇸 Српски', keywords: ['serbian', 'serbia', 'српски'] },
  { value: 'st', label: '🇱🇸 Sesotho', keywords: ['sesotho', 'sotho', 'lesotho'] },
  { value: 'sn', label: '🇿🇼 Shona', keywords: ['shona', 'zimbabwe'] },
  { value: 'sd', label: '🇵🇰 سنڌي', keywords: ['sindhi', 'pakistan', 'سنڌي'] },
  { value: 'si', label: '🇱🇰 සිංහල', keywords: ['sinhala', 'sri lanka', 'සිංහල'] },
  { value: 'sk', label: '🇸🇰 Slovenčina', keywords: ['slovak', 'slovakia', 'slovenčina'] },
  { value: 'sl', label: '🇸🇮 Slovenščina', keywords: ['slovenian', 'slovenia', 'slovenščina'] },
  { value: 'so', label: '🇸🇴 Soomaali', keywords: ['somali', 'somalia', 'soomaali'] },
  { value: 'es', label: '🇪🇸 Español', keywords: ['spanish', 'spain', 'español'] },
  { value: 'es-MX', label: '🇲🇽 Español México', keywords: ['mexican','mexico', 'español mexico', 'mexican'] },
  { value: 'su', label: '🇮🇩 Sunda', keywords: ['sundanese', 'sunda', 'indonesia', 'sunda'] },
  { value: 'sw', label: '🇰🇪 Kiswahili', keywords: ['swahili', 'kiswahili', 'kenya'] },
  { value: 'sv', label: '🇸🇪 Svenska', keywords: ['swedish', 'sweden', 'svenska'] },
  { value: 'tg', label: '🇹🇯 Тоҷикӣ', keywords: ['tajik', 'tajikistan', 'тоҷикӣ'] },
  { value: 'ta', label: '🇮🇳 தமிழ்', keywords: ['tamil', 'india', 'தமிழ்'] },
  { value: 'tt', label: '🇷🇺 Татарча', keywords: ['tatar', 'tatarstan', 'russia', 'татарча'] },
  { value: 'te', label: '🇮🇳 తెలుగు', keywords: ['telugu', 'india', 'తెలుగు'] },
  { value: 'th', label: '🇹🇭 ไทย', keywords: ['thai', 'thailand', 'ไทย'] },
  { value: 'tr', label: '🇹🇷 Türkçe', keywords: ['turkish', 'turkey', 'türkçe'] },
  { value: 'tk', label: '🇹🇲 Türkmençe', keywords: ['turkmen', 'turkmenistan', 'türkmençe'] },
  { value: 'uk', label: '🇺🇦 Українська', keywords: ['ukrainian', 'ukraine', 'українська'] },
  { value: 'ur', label: '🇵🇰 اردو', keywords: ['urdu', 'pakistan', 'اردو'] },
  { value: 'ug', label: '🇨🇳 ئۇيغۇرچە', keywords: ['uyghur', 'uyghurstan', 'china', 'ئۇيغۇرچە'] },
  { value: 'uz', label: '🇺🇿 Oʻzbekcha', keywords: ['uzbek', 'uzbekistan', 'oʻzbekcha'] },
  { value: 'vi', label: '🇻🇳 Tiếng Việt', keywords: ['vietnamese', 'vietnam', 'tiếng việt'] },
  { value: 'cy', label: '🏴 Cymraeg', keywords: ['welsh', 'wales', 'cymraeg'] },
  { value: 'xh', label: '🇿🇦 isiXhosa', keywords: ['xhosa', 'south africa', 'isixhosa'] },
  { value: 'yi', label: '🇮🇱 ייִדיש', keywords: ['yiddish', 'jewish', 'israel', 'ייִדיש'] },
  { value: 'yo', label: '🇳🇬 Yorùbá', keywords: ['yoruba', 'nigeria', 'yorùbá'] },
  { value: 'zu', label: '🇿🇦 isiZulu', keywords: ['zulu', 'south africa', 'isizulu'] }
];
